import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:golden_toolkit/golden_toolkit.dart';
import 'package:vibescape/core/theme/tokens.dart';
import 'package:vibescape/features/player/presentation/widgets/vibe_slider.dart';

/// Golden snapshots for the vibe slider at three representative vibes.
/// The `.png` files are generated by:
///
///   flutter test --update-goldens test/features/player/presentation/vibe_slider_golden_test.dart
///
/// Do NOT commit hand-crafted PNGs — regenerate via the CLI.
void main() {
  testGoldens('VibeSlider renders across mood buckets', (tester) async {
    final builder = DeviceBuilder()
      ..overrideDevicesForAllScenarios(devices: [Device.phone])
      ..addScenario(
        name: 'vibe 20 chill',
        widget: _wrap(const _Sample(value: 20)),
      )
      ..addScenario(
        name: 'vibe 50 steady',
        widget: _wrap(const _Sample(value: 50)),
      )
      ..addScenario(
        name: 'vibe 80 beast',
        widget: _wrap(const _Sample(value: 80)),
      );

    await tester.pumpDeviceBuilder(builder);
    await screenMatchesGolden(tester, 'vibe_slider_moods');
  });
}

Widget _wrap(Widget child) => MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData.dark(useMaterial3: true).copyWith(
        scaffoldBackgroundColor: VibeTokens.bg,
      ),
      home: Scaffold(
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(VibeTokens.s24),
            child: child,
          ),
        ),
      ),
    );

class _Sample extends StatelessWidget {
  const _Sample({required this.value});
  final int value;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 320,
      child: VibeSlider(
        value: value,
        onChanged: (_) {},
        onChangeEnd: (_) {},
      ),
    );
  }
}
