"""Convert a raw HTTP `Cookie:` header string into a Netscape-format
cookies.txt file that yt-dlp / curl / wget can consume.

Grab the cookie value from Edge/Chrome DevTools (Network tab → any request →
Request Headers → Cookie:), save it as a plain text file, then run:

    python scripts/build_cookies_file.py \
        --in  data/yt_cookies_raw.txt \
        --out data/yt_cookies.txt

The output covers `.youtube.com` (subdomain-wide, HTTPS-only, session
cookies since we don't have real expirations from the header alone).
"""

import argparse
from pathlib import Path
from urllib.parse import unquote

NETSCAPE_HEADER = "# Netscape HTTP Cookie File\n# Generated by build_cookies_file.py\n\n"


def parse_cookie_header(raw: str) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for chunk in raw.split(";"):
        chunk = chunk.strip()
        if not chunk or "=" not in chunk:
            continue
        name, value = chunk.split("=", 1)
        name = name.strip()
        value = value.strip()
        if name:
            pairs.append((name, value))
    return pairs


def to_netscape(cookies: list[tuple[str, str]], domain: str = ".youtube.com") -> str:
    lines = [NETSCAPE_HEADER]
    # Fields: domain, include_subdomains, path, https_only, expires, name, value
    for name, value in cookies:
        line = "\t".join([domain, "TRUE", "/", "TRUE", "0", name, value])
        lines.append(line + "\n")
    return "".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--in", dest="in_path", required=True, help="Raw Cookie header text file")
    ap.add_argument("--out", dest="out_path", required=True, help="Netscape cookies.txt to write")
    ap.add_argument("--domain", default=".youtube.com", help="Cookie domain (default: .youtube.com)")
    args = ap.parse_args()

    raw = Path(args.in_path).read_text(encoding="utf-8").strip()
    if raw.lower().startswith("cookie:"):
        raw = raw.split(":", 1)[1].strip()

    cookies = parse_cookie_header(raw)
    if not cookies:
        raise SystemExit(f"[x] no cookies parsed from {args.in_path}")

    text = to_netscape(cookies, domain=args.domain)
    Path(args.out_path).write_text(text, encoding="utf-8")
    print(f"[ok] wrote {len(cookies)} cookies to {args.out_path}")
    print(f"     domain: {args.domain}")
    print("     preview (first 5):")
    for name, value in cookies[:5]:
        print(f"       {name} = {value[:24]}{'...' if len(value) > 24 else ''}")


if __name__ == "__main__":
    main()
